<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class DesignCertificateProp extends Model
{
    protected $table = 'design_certificate_props';
    protected $fillable = [
    "design_certificate_id",
    "certificate_company_name",
    "certificate_company_name_height",
    "certificate_company_name_font_size",
    "certificate_company_name_font_weight",
    "certificate_company_name_font_family",
    "certificate_company_name_margin",
    "certificate_company_name_padding",
    "certificate_company_name_display",
    "certificate_company_name_text_align",
    "certificate_logo",
    "certificate_logo_width",
    "certificate_logo_height",
    "certificate_logo_margin",
    "certificate_logo_padding",
    "certificate_logo_display",
    "certificate_company_address",
    "certificate_company_address_width",
    "certificate_company_address_height",
    "certificate_company_address_font_size",
    "certificate_company_address_font_weight",
    "certificate_company_address_font_family",
    "certificate_company_address_margin",
    "certificate_company_address_padding",
    "certificate_company_address_display",
    "certificate_company_address_text_align",
    "certificate_title",
    "certificate_title_text_align",
    "certificate_title_text",
    "certificate_title_font_family",
    "certificate_title_font_weight",
    "certificate_title_font_size",
    "certificate_title_font_display",
    "certificate_title_margin",
    "certificate_title_padding",
    "certificate_certify_title",
    "certificate_certify_title_text",
    "certificate_certify_text_align",
    "certificate_certify_title_font_family",
    "certificate_certify_title_font_weight",
    "certificate_certify_title_font_size",
    "certificate_certify_title_font_display",
    "certificate_certify_title_margin",
    "certificate_certify_title_padding",
    "certificate_holder_name",
    "certificate_holder_text_align",
    "certificate_holder_font_family",
    "certificate_holder_font_weight",
    "certificate_holder_font_size",
    "certificate_holder_font_display",
    "certificate_holder_margin",
    "certificate_holder_padding",
    "certificate_information",
    "certificate_information_text_align",
    "certificate_information_text",
    "certificate_information_font_family",
    "certificate_information_font_weight",
    "certificate_information_font_size",
    "certificate_information_font_display",
    "certificate_information_margin",
    "certificate_information_padding",
    'certificate_background_image',
    "school_id",
    "created_at",
    "updated_at"];
}
